<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Csir.Spme.Tools.LegacyImport</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <ProjectReference Include="..\..\src\Csir.Spme.Infrastructure\Csir.Spme.Infrastructure.csproj" />
  </ItemGroup>
</Project>
